### ISSUE TITLE
Promises

### ISSUE THREAD

**Issue by jasonkarns** [jdantonio/conf-talk-ideas#1]
I would really love to see a deep talk on Promises in ruby and a comparison/contrast or relation with JS Promises

Maybe there isn't much meat there and is just blog-post sized?

**Comment by jdantonio** [comment]
@jasonkarns Promises are also used in Clojure and Scala, and in all languages not-JavaScript, futures and promises come together as related but slightly different abstractions. So a cross-language comparison could be very interesting. Especially since I just learned today that Microsoft is making extensive use of my gem's promises in the [Azure SDK for Ruby](https://github.com/jdantonio/azure-sdk-for-ruby/blob/master/resource_management/azure_mgmt_compute/lib/azure_mgmt_compute/availability_sets.rb#L78). Wasn't expecting that...

**Comment by jdantonio** [comment]
I've added a new abstract for a talk on promises. I'm going to submit it to both RubyConf and CodeMash.

**Comment by jdantonio** [comment]
This CFP has been submit to RubyConf. Now on to the rest...
